apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv2
  labels:
    app: wordpress
    tier: mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"
  storageClassName: mysql-storage
