apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  serviceName: wordpress-mysql
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      imagePullSecrets:
      - name: ecr-registry
      containers:
      - image: mysql:5.7  # Using the official MySQL image
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: sql-dump
          mountPath: /docker-entrypoint-initdb.d/  # Mount the PVC containing the SQL dump file
      volumes:
        - name: sql-dump
          persistentVolumeClaim:
            claimName: wordpress-sql-dump-pvc  # Reference the PVC
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: ["ReadWriteOnce"]  # Adjusted to ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: mysql-storage

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
      name: mysql
  clusterIP: None
  selector:
    app: wordpress
    tier: mysql
