apiVersion: v1
kind: Pod
metadata:
  name: copy-sql-dump
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - mountPath: /mnt/data
      name: wordpress-sql-dump
  volumes:
  - name: wordpress-sql-dump
    persistentVolumeClaim:
      claimName: wordpress-sql-dump-pvc

