apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod

spec:
  containers:
  - name: ubuntu-sleeper
    image: ubuntu-sleeper
    command: ["sleep"]
    args: ["3600"]
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: dev-secret

# or other way to specify the secret
#   containers:
#   - name: ubuntu-sleeper
#     image: ubuntu-sleeper
#     command: ["sleep"]
#     args: ["3600"]
#     ports:
#     - containerPort: 80
#     env:
#     - name: SECRET_USERNAME
#       valueFrom:
#         secretKeyRef:
#           name: dev-secret
#           key: username
#     - name: SECRET_PASSWORD
#       valueFrom:
#         secretKeyRef:
#           name: dev-secret
#           key: password
