apiVersion: v1
kind: Pod
metadata:
  name: liveness-tcp
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - echo -n "hello" | nc -l -p 9376
    ports:
    - containerPort: 9376
    livenessProbe:
      tcpSocket:
        port: 9376
      initialDelaySeconds: 5
      periodSeconds: 5