apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
  - name: ubuntu-sleeper
    image: ubuntu-sleeper
    command: ["sleep"]
    args: ["3600"]
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: dev-config
    
  nodeSelector:
    env: dev

#   containers:
  # - env:
  #   - name: APP_COLOR
  #     valueFrom:
  #      configMapKeyRef:
  #        name: webapp-config-map
  #        key: APP_COLOR