#  there will be 4 pods 2 in stage and 2 in prod namespace
# there will be 2 services 1 in stage and 1 in prod namespace
#  1 of the pod in stage is connected to stage service and another pod in stage is connected to prod service
#  1 of the pod in prod is connected to prod service and another pod in prod is connected to stage service
# we have to use endpoint slice so connection between pods and services can be established over  different namespaces
---
apiVersion: v1
kind: Namespace
metadata:
  name: stage
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-deployment
  namespace: stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stage
  template:
    metadata:
      labels:
        app: stage
    spec:
      containers:
      - name: nginx-container
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: stage-service
  namespace: stage
spec:
  selector:
    app: stage
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-deployment
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prod
  template:
    metadata:
      labels:
        app: prod
    spec:
      containers:
      - name: nginx-container
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: prod-service
  namespace: prod
spec:
  selector:
    app: prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: EndpointSlice
metadata:
  name: stage-service
  namespace: prod
  labels:
    kubernetes.io/service-name: stage-service
  ownerReferences:
  - apiVersion: v1
    kind: Service
    name: stage-service
    uid: 1a2b3c4d5e6f7g8h9i0j
  creationTimestamp: "2021-06-01T12:00:00Z"
  addressType: IPv4
  ports:
  - name: http
    protocol: TCP
    port: 80
  endpoints:
  - addresses:
    -
      hostname: stage-deployment-1.stage
      targetRef:
        kind: Pod
        name: stage-deployment-1
        namespace: stage
        resourceVersion: "123456"
        uid: 1a2b3c4d5e6f7g8h9i0j
    conditions:
      ready: true
    zone: ap-south-1
  - addresses:
    -
      hostname: prod-deployment-1.prod
      targetRef:
        kind: Pod
        name: prod-deployment-1
        namespace: prod
        resourceVersion: "123456"
        uid: 1a2b3c4d5e6f7g8h9i0j
    conditions:
      ready: true
    zone: ap-south-1
---
apiVersion: v1
kind: EndpointSlice
metadata:
  name: prod-service
  namespace: stage
  labels:
    kubernetes.io/service-name: prod-service
  ownerReferences:
  - apiVersion: v1
    kind: Service
    name: prod-service
    uid: 1a2b3c4d5e6f7g8h9i0j
  creationTimestamp: "2021-06-01T12:00:00Z"
  addressType: IPv4
  ports:
  - name: http
    protocol: TCP
    port: 80
  endpoints:
  - addresses:
    -
      hostname: prod-deployment-2.prod
      targetRef:
        kind: Pod
        name: prod-deployment-2
        namespace: prod
        resourceVersion: "123456"
        uid: 1a2b3c4d5e6f7g8h9i0j
    conditions:
      ready: true
    zone: ap-south-1
  - addresses:
    -
      hostname: stage-deployment-2.stage
      targetRef:
        kind: Pod
        name: stage-deployment-2
        namespace: stage
        resourceVersion: "123456"
        uid: 1a2b3c4d5e6f7g8h9i0j
    conditions:
      ready: true
    zone: ap-south-1