apiVersion: v1
kind: Pod

metadata:
  name: myapp-pod
  labels:
    app: myapp

spec:
  containers:
    - name: nginx-container
      image: nginx
  nodeSelector:
    size: Large

# The nodeSelector field is used to specify a node on which the pod should be scheduled.
# The nodeSelector field is a map of key-value pairs.
# The pod is scheduled on a node only if the node has the key-value pair specified in the nodeSelector field.
# In this example, the pod is scheduled on a node only if the node has the key-value pair size: Large.