apiVersion: v1
kind: Pod

metadata:
  name: myapp-pod
  labels:
    app: myapp

spec:
  containers:
    - name: nginx-container
      image: nginx
  tolerations:
    - key: "envType"
      operator: "Equal"
      value: "prod"
      # effect: "NoSchedule"
      # effect: "NoExecute"
      # effect: "PreferNoSchedule"